#!/bin/zsh

#General
alias cp="cp -i"
alias rm="rm -I"
alias z='zathura 2>/dev/null'
alias v='vim'
alias n='nvim'
alias si='sxiv -q'
alias ls='ls --color=auto -h'
alias grep='grep --color=auto'
alias ip='ip -c'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'

#Shortcuts
alias vv='vim ~/.vim/vimrc'
alias nn='nvim ~/.config/nvim/conf/'
alias s='cd ~/.scripts'
alias mdm='cd ~/misc/suckless/dwm'
alias bk='cd ~/documents/books'
alias lang='cd ~/misc/lang'

#Actions
alias dotf='/usr/bin/git --git-dir=$HOME/repos/dotfiles/ --work-tree=$HOME'
alias now='date +%H:%M:%S'
