#!/bin/zsh

source ~/.cache/wal/colors.sh

#Prompts
PROMPT='%F{$color6}%n %F{$color2}%c %B%F{$color4}->%f '
#PROMPT='%F{$color6}chink %F{$color2}%c %B%F{$color4}->%f '

RPROMPT='\
%F{$color4 }${MODE_INDICATOR_PROMPT}\
%F{$color2 }∙\
%F{$color5 }%M'
