syntax on
set encoding=utf-8
set number relativenumber
set autoread
set nowrap
set incsearch
set hlsearch
set ignorecase
set nocompatible
"set cursorline
set scrolloff=8

set smartindent
set smartcase
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set termguicolors
set updatetime=50
set clipboard+=unnamedplus
"set signcolumn=number

filetype plugin on
set laststatus=2
set noshowmode
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set noswapfile
set undodir=~/.vim/undodir
set undofile
set completeopt=menu,menuone,noselect

" Disables automatic commenting on newline
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Delete trailing whitespace and newlines
autocmd BufWritePre * %s/\s\+$//e
autocmd BufWritepre * %s/\n\+\%$//e

" Key binds and remaps
let mapleader = ' '

cmap <C-k> <UP>
cmap <C-j> <DOWN>

set splitright splitbelow
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <M-j> :resize -2<CR>
nnoremap <M-k> :resize +2<CR>
nnoremap <M-h> :vertical resize +2<CR>
nnoremap <M-l> :vertical resize -2<CR>

" Run program/script:
"map <leader>r :w! \| !runner <c-r>%<CR>

" Plugins:
"
" curl -LSsfo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"
" call plug#begin('~/.vim/autoload/plugged')
" Plug 'vim-airline/vim-airline'
" Plug 'vim-airline/vim-airline-themes'
" Plug 'tpope/vim-surround'
" Plug 'tpope/vim-repeat'
" Plug 'preservim/nerdcommenter'
" Plug 'jiangmiao/auto-pairs'
" Plug 'ap/vim-css-color'
" call plug#end()
