#General
unset MODE_CURSOR_DEFAULT
#VIM_MODE_NO_DEFAULT_BINDINGS=true
KEYTIMEOUT=1
#Cursors
MODE_CURSOR_VIINS="blinking bar"
MODE_CURSOR_VICMD="blinking block"
MODE_CURSOR_VICMD="blinking block"

#Mode indicators for RPS1
MODE_INDICATOR_VIINS='I'
MODE_INDICATOR_VICMD='N'
MODE_INDICATOR_REPLACE='R'
MODE_INDICATOR_SEARCH='S'
MODE_INDICATOR_VISUAL='V'
MODE_INDICATOR_VLINE='V-Line'
